export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const GET_MEDICINE = "GET_MEDICINE"
export const POST_MEDICINE = "POST_MEDICINE"
export const DELETE_MEDICINE = "DELETE_MEDICINE"
export const EDIT_MEDICINE = "EDIT_MEDICINE"
export const LOADING_MEDICINE = "LOADING_MEDICINE"
export const ERROR_MEDICINE = "ERROR_MEDICINE"


export const GET_USER = "GET_USER"
export const POST_USER = "POST_USER"
export const LOADING_USER = "LOADING_USER"
export const ERROE_USER = "ERROE_USER"
export const DELETE_USER = "DELETE_USER"
export const UPDATE_USER = "UPDATE_USER"

export const GET_DOCTOR = "GET_DOCTOR"
export const POST_DOCTOR= "POST_DOCTOR"
export const LOADING_DOCTOR = "LOADING_DOCTOR"
export const ERROE_DOCTOR = "ERROE_DOCTOR"
export const DELETE_DOCTOR = "DELETE_DOCTOR"
export const UPDATE_DOCTOR = "UPDATE_DOCTOR"

