export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

// export const GET_MEDICINE = "GET_MEDICINE"
// export const POST_MEDICINE = "POST_MEDICINE"
// export const LOADING_MEDICINE = "LOADING_MEDICINE"
// export const ERROR_MEDICINE = "ERROR_MEDICINE"

// export const GET_DOCTORS = "GET_DOCTORS"


export const GET_USER = "GET_USER"
export const POST_USER = "POST_USER"
export const LOADING_USER = "LOADING_USER"
export const ERROE_USER = "ERROE_USER"
